name: Build TWRP

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DEVICE: mt5862
  USERNAME: thenevinpie
  REPO_URL: mt5862-twrp
  BRAND: MediaTek

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix permissions and prepare directories
        run: |
          mkdir -p $HOME/twrp
          mkdir -p $HOME/.ccache
          sudo chown -R $USER:$USER $HOME/twrp $HOME/.ccache

      - name: Prepare TWRP source
        run: |
          TWRP_SOURCE="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.3.1-20200222/MinimalOmniRecovery-twrp-6.0-norepo-20200222.tar.xz"
          wget -q ${TWRP_SOURCE} -O $HOME/twrp.tar.xz
          tar -xJf $HOME/twrp.tar.xz --directory $HOME/twrp/ && rm $HOME/twrp.tar.xz

      - name: Copy device tree into TWRP source (inside Docker)
        run: |
          shopt -s extglob
          cp -r $GITHUB_WORKSPACE/!(device|out|.|..) $HOME/twrp/device/MediaTek/mt5862/
          shopt -u extglob

      - name: Build TWRP in Docker
        run: |
          docker pull fr3akyphantom/droid-builder:latest
          docker run --rm -i \
            -e DEVICE=${{ env.DEVICE }} \
            -e USERNAME=${{ env.USERNAME }} \
            -e REPO_URL=${{ env.REPO_URL }} \
            -e BRAND=${{ env.BRAND }} \
            -v "$HOME/twrp:/home/builder/twrp:rw" \
            -v "$HOME/.ccache:/srv/ccache:rw" \
            fr3akyphantom/droid-builder bash << 'EOF'
              cd /home/builder/twrp
              source build/envsetup.sh

              lunch omni_${DEVICE}-userdebug
              make -j$(nproc --all) recoveryimage
          EOF

      - name: Package recovery image
        run: |
          cd $HOME/twrp
          version=$(grep 'define TW_MAIN_VERSION_STR' bootable/recovery/variables.h | cut -d '"' -f2)
          cp out/target/product/${DEVICE}/recovery.img TWRP-${version}-${DEVICE}-$(date +"%Y%m%d")-Unofficial.img

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: twrp-${{ env.DEVICE }}
          path: $HOME/twrp/*.img
