name: Build TWRP recovery

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  USERNAME: thenevinpie
  REPO_URL: mt5862-twrp
  BRAND: MediaTek
  DEVICE: mt5862

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          mkdir -p $HOME/twrp
          TWRP_SOURCE="https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.3.1-20200222/MinimalOmniRecovery-twrp-6.0-norepo-20200222.tar.xz"
          wget -q ${TWRP_SOURCE} -O $HOME/twrp.tar.xz
          tar -xJf $HOME/twrp.tar.xz --directory $HOME/twrp/ && rm $HOME/twrp.tar.xz

      - name: Clone device tree
        run: |
          cd $HOME/twrp/
          rm -rf device/${BRAND}/${DEVICE} || true
          git clone https://github.com/${USERNAME}/${REPO_URL}.git device/${BRAND}/${DEVICE}
          rm -rf bootable/recovery
          git clone https://github.com/omnirom/android_bootable_recovery -b android-9.0 --depth 1 bootable/recovery
      
      - name: Fix permissions
        run: |
          sudo chown -R $USER:$USER $HOME/twrp
          mkdir -p $HOME/.ccache
          sudo chown -R $USER:$USER $HOME/.ccache

      - name: Run build inside Docker
        run: |
          docker run --rm -i \
            -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) \
            -e DEVICE=${DEVICE} -e BRAND=${BRAND} -e USERNAME=${USERNAME} -e REPO_URL=${REPO_URL} \
            -v "$HOME/twrp:/home/builder/twrp/:rw,z" \
            -v "$HOME/.ccache:/srv/ccache:rw,z" \
            fr3akyphantom/droid-builder bash << 'EOF'
              cd /home/builder/twrp/
              source build/envsetup.sh
              lunch omni_${DEVICE}-userdebug
              make -j$(nproc --all) recoveryimage
          EOF


      - name: Package output
        run: |
          cd $HOME/twrp/
          version=$(grep 'define TW_MAIN_VERSION_STR' bootable/recovery/variables.h | cut -d '"' -f2)
          cp out/target/product/${DEVICE}/recovery.img TWRP-${version}-${DEVICE}-$(date +"%Y%m%d")-Unofficial.img

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: twrp-${{ env.DEVICE }}
          path: $HOME/twrp/*.img
